### ISSUE TITLE
Star Bar Score misaligned on Android

### ISSUE THREAD

**Issue by daleabellaa** [KoolieAid/HelpfulLibrarian#80]
This may be what the screening panelists have encountered. **Theory:** On the main level scene, under Status Panel Main maybe the positions of _StarScoreStatus_ (the score bar that shows in tutorial) & _StarScore_ (the actual score bar that shows in the main levels) are not exactly aligned after the results screen animation (stars / score fall down into the notebook)

edit: the build is updated and pulled from main (April 8)
![star bar misaligned](https://user-images.githubusercontent.com/89574293/230706525-9bfb779c-5c3d-4ddb-94c9-24f8bd10ba6c.jpg)
![starscorestatus](https://user-images.githubusercontent.com/89574293/230706726-d2d2d406-3885-4c8b-b7e6-2c70e8c374ee.jpg)

**Comment by KoolieAid** [comment]
this on recent build?

**Comment by daleabellaa** [comment]
okay thanks can help with testing, just update me whenever
